// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQ1E1PGs1yYAQUYqQjUGBRG1mNS91ul0',
    appId: '1:126061674996:web:18da87886f9a0010db39a1',
    messagingSenderId: '126061674996',
    projectId: 'flutter-prep-4b04b',
    authDomain: 'flutter-prep-4b04b.firebaseapp.com',
    databaseURL: 'https://flutter-prep-4b04b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-4b04b.firebasestorage.app',
    measurementId: 'G-V5PGJCCH4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvM73qrM_akNovFho37zE6QOjgM1KEEtA',
    appId: '1:126061674996:android:91aef130c190391fdb39a1',
    messagingSenderId: '126061674996',
    projectId: 'flutter-prep-4b04b',
    databaseURL: 'https://flutter-prep-4b04b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-4b04b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxwcv62R0i05fgfifiYh2hjUc-r-Vhz0',
    appId: '1:126061674996:ios:5016b872e5f436f8db39a1',
    messagingSenderId: '126061674996',
    projectId: 'flutter-prep-4b04b',
    databaseURL: 'https://flutter-prep-4b04b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-4b04b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxwcv62R0i05fgfifiYh2hjUc-r-Vhz0',
    appId: '1:126061674996:ios:5016b872e5f436f8db39a1',
    messagingSenderId: '126061674996',
    projectId: 'flutter-prep-4b04b',
    databaseURL: 'https://flutter-prep-4b04b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-4b04b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQ1E1PGs1yYAQUYqQjUGBRG1mNS91ul0',
    appId: '1:126061674996:web:5cbf16c2798114f6db39a1',
    messagingSenderId: '126061674996',
    projectId: 'flutter-prep-4b04b',
    authDomain: 'flutter-prep-4b04b.firebaseapp.com',
    databaseURL: 'https://flutter-prep-4b04b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-4b04b.firebasestorage.app',
    measurementId: 'G-C71T2FF48B',
  );
}
